[package]
name = "spy"
version = "0.1.0"
authors = ["taoyu <t1997y@vip.qq.com>"]
edition = "2018"

[lib]
name = "spy"
path = "lib.rs"

[[example]]
name = "capture"
path = "examples/capture.rs"

[build-dependencies]
bindgen = "0.52"
cc = "1.0"